# This is a basic workflow to help you get started with Actions

name: React CI

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install npm dependencies
      run: npm install
      
    - name: Typescript check
      run: npm run typescript

    - name: Run ESLint
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build --if-present
